### ISSUE TITLE
1D Toy Example Code Missing from OpenReview

### ISSUE THREAD

**Issue by brendanwallison** [ZongyuGuo/Versatile-NP#1]
Hello,

The readme states that "The code for 1D toy examples can be found in the [supplementary material of our Openreview submission](https://openreview.net/forum?id=2nLeOOfAjK)."

When I click through and download "2459_versatile_neural_processes_for-Supplementary Material.zip", the only item is  "Versatile_NP_Camera_Ready_Appendix.pdf". This appendix contains detailed experimental settings, among other things, but no code. Is there somewhere else that I should be looking instead for the 1D example code?

Thank you!

**Comment by ZongyuGuo** [comment]
Hi, now the 1D code can be accessed via the google drive link, together wth 3D checkpoints. Note that the 1D code has not been cleaned up in detail. Hope you will find it useful.

**Comment by brendanwallison** [comment]
Thank you!

**Comment by JohnLaMaster** [comment]
Was the 1d code taken down? There are only 6 files in the drive, 2 each for lamps, cars, and chairs.

**Comment by ZongyuGuo** [comment]
It is still there. 
Or you can download through this link:
https://drive.google.com/file/d/1IGMMTTLCUXY0k7_Zxj3KX970SD-fr2nO/view?usp=share_link
